[sTextBlack]
StringAlign=Center
StringEffect=None
StringStyle=Italic
FontFace=Elephant
FontSize=10
FontColor=0,0,0
AntiAlias=1

[sTextWhite]
StringAlign=Center
StringEffect=None
StringStyle=Italic
FontFace=Elephant
FontSize=10
FontColor=255,255,255
AntiAlias=1

[sTextDayWhite]
StringAlign=Left
StringEffect=None
StringStyle=Italic
FontFace=Elephant
FontSize=20
FontColor=255,255,255
AntiAlias=1

[sTextWWhite]
StringAlign=Left
StringEffect=None
StringStyle=Italic
FontFace=Elephant
FontSize=10
FontColor=255,255,255
AntiAlias=1
clipstring=1
w=130
h=50
ToolTipText="%4"

[sTextWBlack]
StringAlign=Left
StringEffect=None
StringStyle=Italic
FontFace=Elephant
FontSize=10
FontColor=0,0,0
AntiAlias=1
clipstring=1
w=130
h=50
ToolTipText="%3"

[mBackground]
Measure=calc
Formula=1
UpdateDivider=-1

[sWeatherBackgroundDivider]
DynamicVariables=1
LineWidth=3
LineLength=304
LineStart=203
LineColor=0,0,0,100
AntiAlias=1
Solid=0
X = 307
Y = 307
UpdateDivider=-1

[sWeatherBackgroundRing]
StartAngle=-0
RotationAngle=6.283185
LineColor=0,0,0,100
AntiAlias=1
Solid=1
W=614
H=614
UpdateDivider=-1

[sSpecsBackgroundRing]
StartAngle=-0
RotationAngle=6.283185
LineColor=0,0,0,100
AntiAlias=1
Solid=1
W=322
H=322
UpdateDivider=-1

[sNetBackgroundRing]
StartAngle=-0
RotationAngle=6.283185
LineColor=0,0,0,100
AntiAlias=1
Solid=1
W=388
H=388
UpdateDivider=-1