[Variables]
DiskHighest=
NetUp=
NetDown=
ZIP=
APIKey=
CPUName=
GPUName=

[sTextBlack]
StringAlign=Center
StringEffect=None
StringStyle=Italic
FontFace=Elephant
FontSize=10
FontColor=0,0,0
AntiAlias=1

[sTextWhite]
StringAlign=Center
StringEffect=None
StringStyle=Italic
FontFace=Elephant
FontSize=10
FontColor=255,255,255
AntiAlias=1

[sTextDayWhite]
StringAlign=Left
StringEffect=None
StringStyle=Italic
FontFace=Elephant
FontSize=20
FontColor=255,255,255
AntiAlias=1

[sTextWWhite]
StringAlign=Left
StringEffect=None
StringStyle=Italic
FontFace=Elephant
FontSize=10
FontColor=255,255,255
AntiAlias=1
clipstring=1
w=130
h=50
ToolTipText="%4"

[sTextWBlack]
StringAlign=Left
StringEffect=None
StringStyle=Italic
FontFace=Elephant
FontSize=10
FontColor=0,0,0
AntiAlias=1
clipstring=1
w=130
h=50
ToolTipText="%3"

[mBackground]
Measure=calc
Formula=1
UpdateDivider=-1

[mWeatherBackground]
DynamicVariables=1
LineColor=0,0,0,100
AntiAlias=1
Solid=0
UpdateDivider=-1
H=1024
W=1280
